services:

  db:
    image: postgres:17-alpine
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  api:
    image: ${DOCKERHUB_USERNAME}/caveo-backend:latest
    ports:
      - "3000:3000"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DOCKERHUB_USERNAME: ${DOCKERHUB_USERNAME}
      COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID}
      COGNITO_CLIENT_SECRET: ${COGNITO_CLIENT_SECRET}
      USER_POOL_ID: ${USER_POOL_ID}
      COGNITO_ADMIN_ACCESS_KEY: ${COGNITO_ADMIN_ACCESS_KEY}
      COGNITO_ADMIN_SECRET_ACCESS_KEY: ${COGNITO_ADMIN_SECRET_ACCESS_KEY}
    depends_on:
      - db
